{{- if and .Values.certificate.create .Values.service.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "prometheus.certificate.name" . }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
    {{- with .Values.certificate.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.certificate.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  secretName: {{ include "prometheus.certificate.secretName" . }}
  {{- with .Values.certificate.dnsNames }}
  dnsNames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.certificate.issuerRef }}
  issuerRef:
    kind: {{ default "ClusterIssuer" .kind }}
    name: {{ include "prometheus.certificate.issuerRefName" $ }}
  {{- end }}
{{- end }}
