{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "prometheus.fullname" . }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
    {{- with .Values.rbac.labels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: ['']
    verbs: ['get', 'list', 'watch']
    resources:
      - nodes
      - nodes/proxy
      - nodes/metrics
      - services
      - endpoints
      - pods
      - configmaps
  - apiGroups: ['extensions', 'networking.k8s.io']
    verbs: ['get', 'list', 'watch']
    resources:
      - ingresses
      - ingresses/status
  - nonResourceURLs: ['/metrics']
    verbs: ['get']
{{- end -}}
